### PR TITLE
create logon page

### PR DESCRIPTION
**Pull request by abhisheknaik1812**
completes logon page functionality. Please review and merge the code @abhirocksf5

### CODE REVIEW

**Review by abhirocksf5 — CHANGES_REQUESTED** [review]
@abhisheknaik1812 : Picture is missing in logon page.

**Comment by abhisheknaik1812** [comment]
@abhirocksf5  : Changes are done. Please review and merge the code.

**Review by abhisheknaik1812 — COMMENTED** [review]
@abhirocksf5  : Please review . Image is updated.

**Review by abhirocksf5 — APPROVED** [review]
@abhisheknaik1812  : great job. Approved

**Pull request merged**
